version: 2.1
orbs:
  anchore: anchore/anchore-engine@1
executors:
  env-publisher:
    environment:
      IMAGE_NAME: vishnusk/devsecops-lab
jobs:
  zap-test:
    executor: env-publisher
    machine: true
    steps:
      - checkout
      - run:
          name: branch-build
          command: |
            docker network create zapnet
            IMAGE_TAG=$CIRCLE_BRANCH
            docker build -t $IMAGE_NAME .
      - run:
          name: zap-test
          shell: /bin/bash
          command: |
            docker images
            echo $CIRCLE_BRANCH
            docker run --net zapnet --name labimg -d -p 80:80 $IMAGE_NAME
            docker run --net zapnet -t owasp/zap2docker-weekly zap-full-scan.py -t http://$(ip -f inet -o addr show docker0 | awk '{print $4}' | cut -d '/' -f 1)/xvwa > scan.txt
            cat scan.txt
          no_output_timeout: 60m
      - run:
          name: check-xss
          shell: /bin/bash
          command: |
            cat scan.txt
            val=$(cat scan.txt | grep "WARN-NEW: Cross Site Scripting")
            
            echo $val
            if [ -z "$val" ]
            then
              echo "you cleared the vulnerability. Good Work!"
            else
              echo "stopped"
              exit 1
            fi
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  anchore_local_image_scan:
    executor: anchore/anchore_engine
    steps:
      - setup_remote_docker
      - checkout
      - run:
          command: 'docker build -t "devsecops-lab/anchore:latest" .'
          name: build container
      - anchore/analyze_local_image:
          image_name: 'devsecops-lab/anchore:latest'
          policy_failure: true
          timeout: '500'
      - anchore/parse_reports
      - store_artifacts:
          path: anchore-reports
      - run:
          name: report analysis
          command: |
            ls anchore-reports
            if ls anchore-reports/*vuln*.json >/dev/null 2>&1; then
              exit 1
            fi

  clair_local_image_scan:
    executor: env-publisher
    machine: true
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Clair Local Scan 
          command: |
            docker run -p 5432:5432 -d --name db arminc/clair-db:latest
            docker run -p 6060:6060 --link db:postgres -d --name clair arminc/clair-local-scan:latest
            cat /etc/os-release
            uname -a

  docker-build-publish:
    executor: env-publisher
    machine: true
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            IMAGE_TAG="v${CIRCLE_BUILD_NUM}"
            echo "$DOCKER_PWD" | docker login -u "$DOCKER_UNAME" --password-stdin 
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$IMAGE_TAG
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$IMAGE_TAG
            curl -X POST "http://admin:11de256effe0dcfa0a0ba378d1834139a5@web-server-loadbalancer-1056389698.us-east-2.elb.amazonaws.com:8080/job/devsecops-lab/build"
workflows:
  version: 2
  build-master:
    jobs:
      - zap-test
      - anchore_local_image_scan
      - clair_local_image_scan
      - docker-build-publish:
          context:
            - test
          requires:
            - zap-test
            - anchore_local_image_scan
            - clair_local_image_scan
